//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleNotifier.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowBattleDialog {
            get {
                return ((bool)(this["ShowBattleDialog"]));
            }
            set {
                this["ShowBattleDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowMapDialog {
            get {
                return ((bool)(this["ShowMapDialog"]));
            }
            set {
                this["ShowMapDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlayNotificationSound {
            get {
                return ((bool)(this["PlayNotificationSound"]));
            }
            set {
                this["PlayNotificationSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public decimal DialogLifeSeconds {
            get {
                return ((decimal)(this["DialogLifeSeconds"]));
            }
            set {
                this["DialogLifeSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SoundPath {
            get {
                return ((string)(this["SoundPath"]));
            }
            set {
                this["SoundPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NotificationDuration {
            get {
                return ((int)(this["NotificationDuration"]));
            }
            set {
                this["NotificationDuration"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CloseDialogTime {
            get {
                return ((bool)(this["CloseDialogTime"]));
            }
            set {
                this["CloseDialogTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1All battle types\r\n0Normal\r\n0One-life\r\n0First finish\r\n0Slowness\r\n0Survivor\r\n0Last" +
            " counts\r\n0Finish-count\r\n01 hour tt\r\n0Flag tag\r\n0Apple\r\n0Speed")]
        public string BattleTypes {
            get {
                return ((string)(this["BattleTypes"]));
            }
            set {
                this["BattleTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1All designers")]
        public string Designers {
            get {
                return ((string)(this["Designers"]));
            }
            set {
                this["Designers"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlackList {
            get {
                return ((string)(this["BlackList"]));
            }
            set {
                this["BlackList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-Nico-o\r\n-Tony-\r\n5tr1k3r\r\n8-ball\r\nAbula\r\nadi\r\nAKB\r\nAli\r\nAlma\r\nalvin\r\nANATOLIY\r\nan" +
            "pdad\r\nApelgam\r\nAre\r\nastral-r\r\naxxu\r\nbadyl\r\nbarryp\r\nBarTek\r\nBbl Bce CyKu\r\nbEAT\r\nB" +
            "ENNY\r\nBismuth\r\nBjenn\r\nBludek\r\nBoneLESS\r\nBoomer\r\nCap\r\nCfilorvy\r\nChaza\r\nChip\r\nCoco" +
            "\r\nCSabi\r\nDaFred\r\nDariuz\r\nDash\r\nDCEM\r\nDead One\r\nDeath\r\nDed\r\nDomi\r\nDRACON\r\nDrakula" +
            "\r\nDreamHunter\r\nDynamo\r\ndz\r\nEcchi\r\nEddi\r\nElfy\r\nElrondMcBong\r\nepp\r\nerror\r\nExTeC\r\nf" +
            "abio\r\nFanatico\r\nFecal\r\nfinman\r\nFredrik\r\nGiancarlo\r\ngimp\r\nGraduS\r\nGrindelwald\r\nGR" +
            "ob\r\nHaruhi\r\nhehe\r\nHonza\r\nHosp\r\nIce\r\nigge\r\ninf3rno\r\ninfected\r\nInferno\r\nIsmo\r\nItha" +
            "l\r\nJ-sim\r\nJalli\r\nJamppa\r\nJappe2\r\nJarkko\r\njaytea\r\njblaze\r\nJeppe\r\nJohn\r\nJohnny\r\njo" +
            "nsta\r\njonsykkel\r\nJSmith\r\nJuish\r\njuka\r\nJuzam\r\nk0en\r\nk00\r\nkabii\r\nKazan\r\nkd\r\nKejebr" +
            "a\r\nkestas\r\nKiiwi\r\nKingy\r\nKoopa\r\nKopaka\r\nKostyak\r\nKowal\r\nkuchitsu\r\nKuper\r\nKuri\r\nL" +
            "abs\r\nLazY\r\nLeek\r\nLousku\r\nLukazz\r\nLumen\r\nLuther\r\nMaala\r\nMadMad\r\nMadness\r\nMagb\r\nma" +
            "gicman\r\nMarian\r\nMarkku\r\nMats\r\nMawane\r\nMax\r\nMaximus\r\nmcleod\r\nMemphis\r\nMicroGen\r\nM" +
            "ielz\r\nMika\r\nmikl\r\nmilagros\r\nMJXII\r\nMochi\r\nMorgan\r\nMoszat\r\nMP\r\nMpq\r\nmr\r\nMrrrr\r\nMu" +
            "nkki\r\nNaDiRu\r\nNekit\r\nnick-o-matic\r\nNightMar\r\nniN\r\nnobody\r\nnoni\r\nnozkey\r\nofta\r\nOl" +
            "d_Bjorn\r\nonla\r\nOrcc\r\np-skript\r\nPab\r\nPascal\r\nPawq\r\nPeacemaker\r\nPek\r\nPELUSON27\r\nPh" +
            "illip\r\nPJ\r\nPlayer\r\nPlayer1\r\nPolarix\r\nproDigy\r\nPunxer\r\nQuantz\r\nRaane\r\nRamone\r\nRam" +
            "zi\r\nRasken\r\nRast\r\nRaven\r\nribot\r\nrobbla\r\nromy4\r\nRooker\r\nroope\r\nRopelli\r\nSalsa\r\nSC" +
            "ASI\r\nschiz\r\nschnon\r\nSchumi\r\nsemyr\r\nSIC\r\nSick_Mambo\r\nSienna\r\nskint0r\r\nsla\r\nSmibu\r" +
            "\nsnajdig\r\nSORIN283\r\nSouza\r\nStaar\r\nstefankivb\r\nStini\r\nSuharice\r\nSveinR\r\ntalli\r\nta" +
            "mugol1\r\nTarGEnoR\r\ntatujka\r\nteajay\r\nterb0\r\nThanaTos\r\nThe OooO\r\nThunder\r\nTigro\r\nTi" +
            "sk\r\nTL\r\nTm\r\ntotem\r\ntrew\r\nTTechnik\r\nTuA\r\ntubby\r\nUlaanaa\r\numiz\r\nUncle Milty\r\nundi\r" +
            "\nVALDO\r\nveezay\r\nVes\r\nville_j\r\nVirus\r\nVT\r\nWacco\r\nwazsi\r\nWeep\r\nwjelo\r\nXhomaz\r\nXiph" +
            "ias\r\nxonii\r\nYEAHS\r\nyohanu\r\nYoni\r\nyoosef\r\nyOwie\r\nyuno uno\r\nzebra\r\nzelterboij\r\nZer" +
            "o\r\nZerox\r\nZid\r\nZox\r\nZweq\r\nzwor")]
        public string AutocompleteKuskis {
            get {
                return ((string)(this["AutocompleteKuskis"]));
            }
            set {
                this["AutocompleteKuskis"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MapSize {
            get {
                return ((int)(this["MapSize"]));
            }
            set {
                this["MapSize"] = value;
            }
        }
    }
}
